#!/bin/bash

echo "system report generated by $USERNAME, $DATETIME"
HOSTNAME=$(hostname)
echo " My hostname is $HOSTNAME"
OS=$(source /etc/os-release && echo $NAME $VERSION)
echo " current os is $OS"
UPTIME=$(uptime -p)
echo " uptime is $UPTIME"
